# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'training.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(756, 504)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Utama = QtWidgets.QWidget(self.centralwidget)
        self.Utama.setStyleSheet("background-color:#DAD7CD;")
        self.Utama.setObjectName("Utama")
        self.LeftMenu = QtWidgets.QWidget(self.Utama)
        self.LeftMenu.setGeometry(QtCore.QRect(20, 90, 131, 301))
        self.LeftMenu.setStyleSheet("background-color:#3A5A40;\n"
"border-radius:15px;")
        self.LeftMenu.setObjectName("LeftMenu")
        self.btnTraining = QtWidgets.QPushButton(self.LeftMenu)
        self.btnTraining.setGeometry(QtCore.QRect(20, 90, 91, 31))
        self.btnTraining.setStyleSheet("background-color:#A3B18A;\n"
"text-weight: bold;\n"
"border-radius:10px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../training.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTraining.setIcon(icon)
        self.btnTraining.setObjectName("btnTraining")
        self.btnTesting = QtWidgets.QPushButton(self.LeftMenu)
        self.btnTesting.setGeometry(QtCore.QRect(20, 160, 91, 31))
        self.btnTesting.setStyleSheet("background-color:#A3B18A;\n"
"text-weight: bold;\n"
"border-radius:10px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../testing.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTesting.setIcon(icon1)
        self.btnTesting.setObjectName("btnTesting")
        self.judul_2 = QtWidgets.QLabel(self.LeftMenu)
        self.judul_2.setGeometry(QtCore.QRect(20, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.judul_2.setFont(font)
        self.judul_2.setStyleSheet("color: white;\n"
"")
        self.judul_2.setObjectName("judul_2")
        self.judul = QtWidgets.QLabel(self.Utama)
        self.judul.setGeometry(QtCore.QRect(300, 20, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.judul.setFont(font)
        self.judul.setObjectName("judul")
        self.textEdit = QtWidgets.QTextEdit(self.Utama)
        self.textEdit.setGeometry(QtCore.QRect(190, 90, 511, 251))
        self.textEdit.setObjectName("textEdit")
        self.btnTraining_2 = QtWidgets.QPushButton(self.Utama)
        self.btnTraining_2.setGeometry(QtCore.QRect(610, 360, 91, 31))
        self.btnTraining_2.setStyleSheet("background-color:#344E41;\n"
"text-weight: bold;\n"
"color :white;\n"
"border-radius:10px;")
        self.btnTraining_2.setObjectName("btnTraining_2")
        self.Utama_2 = QtWidgets.QWidget(self.Utama)
        self.Utama_2.setGeometry(QtCore.QRect(0, 0, 738, 466))
        self.Utama_2.setStyleSheet("background-color:#DAD7CD;")
        self.Utama_2.setObjectName("Utama_2")
        self.LeftMenu_2 = QtWidgets.QWidget(self.Utama_2)
        self.LeftMenu_2.setGeometry(QtCore.QRect(20, 90, 131, 301))
        self.LeftMenu_2.setStyleSheet("background-color:#3A5A40;\n"
"border-radius:15px;")
        self.LeftMenu_2.setObjectName("LeftMenu_2")
        self.btnTraining_3 = QtWidgets.QPushButton(self.LeftMenu_2)
        self.btnTraining_3.setGeometry(QtCore.QRect(20, 90, 91, 31))
        self.btnTraining_3.setStyleSheet("background-color:#A3B18A;\n"
"text-weight: bold;\n"
"border-radius:10px;")
        self.btnTraining_3.setIcon(icon)
        self.btnTraining_3.setObjectName("btnTraining_3")
        self.btnTesting_2 = QtWidgets.QPushButton(self.LeftMenu_2)
        self.btnTesting_2.setGeometry(QtCore.QRect(20, 160, 91, 31))
        self.btnTesting_2.setStyleSheet("background-color:#A3B18A;\n"
"text-weight: bold;\n"
"border-radius:10px;")
        self.btnTesting_2.setIcon(icon1)
        self.btnTesting_2.setObjectName("btnTesting_2")
        self.judul_3 = QtWidgets.QLabel(self.LeftMenu_2)
        self.judul_3.setGeometry(QtCore.QRect(20, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.judul_3.setFont(font)
        self.judul_3.setStyleSheet("color: white;\n"
"")
        self.judul_3.setObjectName("judul_3")
        self.judul_4 = QtWidgets.QLabel(self.Utama_2)
        self.judul_4.setGeometry(QtCore.QRect(300, 20, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.judul_4.setFont(font)
        self.judul_4.setObjectName("judul_4")
        self.textEdit_2 = QtWidgets.QTextEdit(self.Utama_2)
        self.textEdit_2.setGeometry(QtCore.QRect(190, 90, 511, 251))
        self.textEdit_2.setObjectName("textEdit_2")
        self.btnTraining_4 = QtWidgets.QPushButton(self.Utama_2)
        self.btnTraining_4.setGeometry(QtCore.QRect(610, 360, 91, 31))
        self.btnTraining_4.setStyleSheet("background-color:#344E41;\n"
"text-weight: bold;\n"
"color :white;\n"
"border-radius:10px;")
        self.btnTraining_4.setObjectName("btnTraining_4")
        self.widget = QtWidgets.QWidget(self.Utama_2)
        self.widget.setGeometry(QtCore.QRect(190, 360, 401, 31))
        self.widget.setStyleSheet("background-color:#588157;\n"
"border-radius:5px;")
        self.widget.setObjectName("widget")
        self.progres = QtWidgets.QLabel(self.widget)
        self.progres.setGeometry(QtCore.QRect(10, 5, 381, 21))
        self.progres.setText("")
        self.progres.setObjectName("progres")
        self.Class = QtWidgets.QLabel(self.Utama_2)
        self.Class.setGeometry(QtCore.QRect(200, 400, 401, 41))
        self.Class.setText("")
        self.Class.setObjectName("Class")
        self.horizontalLayout.addWidget(self.Utama)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnTraining.setText(_translate("MainWindow", "Training"))
        self.btnTesting.setText(_translate("MainWindow", "Testing"))
        self.judul_2.setText(_translate("MainWindow", "Menu"))
        self.judul.setText(_translate("MainWindow", "SISTEM KLASIFIKASI SAMPAH"))
        self.btnTraining_2.setText(_translate("MainWindow", "Training"))
        self.btnTraining_3.setText(_translate("MainWindow", "Training"))
        self.btnTesting_2.setText(_translate("MainWindow", "Testing"))
        self.judul_3.setText(_translate("MainWindow", "Menu"))
        self.judul_4.setText(_translate("MainWindow", "SISTEM KLASIFIKASI SAMPAH"))
        self.btnTraining_4.setText(_translate("MainWindow", "Training"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
