# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'training.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(756, 504)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Utama = QtWidgets.QWidget(self.centralwidget)
        self.Utama.setStyleSheet("background-color:#DAD7CD;")
        self.Utama.setObjectName("Utama")
        self.judul = QtWidgets.QLabel(self.Utama)
        self.judul.setGeometry(QtCore.QRect(220, 20, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.judul.setFont(font)
        self.judul.setObjectName("judul")
        self.textEdit = QtWidgets.QTextEdit(self.Utama)
        self.textEdit.setGeometry(QtCore.QRect(30, 90, 511, 251))
        self.textEdit.setObjectName("textEdit")
        self.tombol_train = QtWidgets.QPushButton(self.Utama)
        self.tombol_train.setGeometry(QtCore.QRect(450, 360, 91, 31))
        self.tombol_train.setStyleSheet("background-color:#344E41;\n"
"text-weight: bold;\n"
"color :white;\n"
"border-radius:10px;")
        self.tombol_train.setObjectName("tombol_train")
        self.widget = QtWidgets.QWidget(self.Utama)
        self.widget.setGeometry(QtCore.QRect(30, 360, 401, 31))
        self.widget.setStyleSheet("background-color:#588157;\n"
"border-radius:5px;")
        self.widget.setObjectName("widget")
        self.progres = QtWidgets.QLabel(self.widget)
        self.progres.setGeometry(QtCore.QRect(10, 0, 381, 21))
        self.progres.setText("")
        self.progres.setObjectName("progres")
        self.LeftMenu_2 = QtWidgets.QWidget(self.Utama)
        self.LeftMenu_2.setGeometry(QtCore.QRect(580, 90, 131, 301))
        self.LeftMenu_2.setStyleSheet("background-color:#3A5A40;\n"
"border-radius:15px;")
        self.LeftMenu_2.setObjectName("LeftMenu_2")
        self.btn_Training = QtWidgets.QPushButton(self.LeftMenu_2)
        self.btn_Training.setGeometry(QtCore.QRect(20, 90, 91, 31))
        self.btn_Training.setStyleSheet("background-color:#A3B18A;\n"
"text-weight: bold;\n"
"border-radius:10px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../training.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Training.setIcon(icon)
        self.btn_Training.setObjectName("btn_Training")
        self.btn_Testing = QtWidgets.QPushButton(self.LeftMenu_2)
        self.btn_Testing.setGeometry(QtCore.QRect(20, 160, 91, 31))
        self.btn_Testing.setStyleSheet("background-color:#A3B18A;\n"
"text-weight: bold;\n"
"border-radius:10px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../testing.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Testing.setIcon(icon1)
        self.btn_Testing.setObjectName("btn_Testing")
        self.Menu = QtWidgets.QLabel(self.LeftMenu_2)
        self.Menu.setGeometry(QtCore.QRect(20, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Menu.setFont(font)
        self.Menu.setStyleSheet("color: white;\n"
"")
        self.Menu.setObjectName("Menu")
        self.Class = QtWidgets.QLabel(self.Utama)
        self.Class.setGeometry(QtCore.QRect(30, 400, 401, 41))
        self.Class.setText("")
        self.Class.setObjectName("Class")
        self.horizontalLayout.addWidget(self.Utama)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.judul.setText(_translate("MainWindow", "SISTEM KLASIFIKASI SAMPAH"))
        self.tombol_train.setText(_translate("MainWindow", "Training"))
        self.btn_Training.setText(_translate("MainWindow", "Training"))
        self.btn_Testing.setText(_translate("MainWindow", "Testing"))
        self.Menu.setText(_translate("MainWindow", "Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
